logo: /logo.png
title: MusicDoc
description: Simple markup format for music
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  owner_url: https://github.com/MusicDoc/MusicDoc