logo: /logo.png
title: MusicDoc
description: Simple markup format for music
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: true
  owner_url: https://github.com/MusicDoc/MusicDoc